name: Build and Deploy
# 触发器
on: 
  push:
# 任务  
jobs:
  build-and-deploy:
  	# 环境
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2.3.1
      
    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Add packages
      run: npm install


作者：弗兰肯斯坦
链接：https://juejin.cn/post/6950551485356703751
来源：稀土掘金
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
