name: Build and Deploy
# 触发器
on: 
  push:
  # 定时器 可以指定时间触发工作流
  # https://crontab.guru/examples.html 有一些例子可供参考
  schedule: 
    - cron: '0 22 * * *'
jobs:
  build-and-deploy:
  	# 环境
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2.3.1
      
    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Get suggestion
      run: npm install && npm run suggestion

- name: Send email
  uses: dawidd6/action-send-mail@v3.6.0
 with:
  	# smtp 服务器地址
    server_address: smtp.163.com
    server_port: 465
    # 账号密码
    username: ${{secrets.MAIL_USERNAME}}
    password: ${{secrets.MAIL_PASSWORD}}
    # 标题
    subject: 今日穿衣建议
    # 发送的内容
    body: file://index.html
    # 目标邮箱
    to: 675632418@qq.com
    from: 163
    content_type: text/html
    convert_markdown: true
